In [1]:
import numpy as np

## numpy array

In [2]:
benimListem = [20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [5]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [6]:
matrixListesi[1][0]

20

In [7]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [9]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace

In [18]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

## eye

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## random

In [22]:
np.random.rand(3)

array([0.97740677, 0.78616116, 0.75501639])

In [24]:
np.random.rand(3,3)

array([[0.27100709, 0.2510527 , 0.89010158],
       [0.69869814, 0.67069   , 0.51461011],
       [0.6604751 , 0.19895417, 0.54565198]])

In [25]:
np.random.randint(1,10)

5

In [26]:
np.random.randint(1,10,5)

array([2, 6, 8, 4, 8])

In [27]:
benimNumpyDizim = np.arange(30)

In [28]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
benimRandomDizim = np.random.randint(0,100,30)

In [30]:
benimRandomDizim

array([37, 75, 14, 57, 11, 47, 36, 43, 96, 90,  9, 80, 51, 17, 11, 58, 23,
       52, 84, 11, 69,  6,  3, 40, 40, 64, 67, 82, 71, 58])

## numpy dizi methodları

In [32]:
benimNumpyDizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [33]:
benimNumpyDizim.max()

29

In [34]:
benimRandomDizim.max()

96

In [35]:
benimRandomDizim.min()

3

In [36]:
benimRandomDizim.argmax()

8

In [37]:
benimRandomDizim.argmin()

22

In [38]:
benimNumpyDizim.shape

(30,)