In [39]:
import numpy as np = -5

In [40]:
benimDizim = np.arange(0,15)

In [41]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
benimDizim[5]

5

In [43]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [44]:
benimDizim[3:8] = -5

In [45]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [46]:
baskaDizi = np.arange(0,24)

In [47]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [48]:
slicingDizisi = baskaDizi[4:9]

In [49]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [50]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [51]:
slicingDizisi[:] = 700

In [52]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [53]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [54]:
ornekDizi = np.arange(0,24)

In [55]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [56]:
ornekDiziKopyasi = ornekDizi.copy()

In [57]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [58]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [60]:
ornekDiziKopyaSlicing[:] = 800

In [61]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [62]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [63]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [64]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [65]:
ornekMatrixDizim = np.array(benimListem)

In [66]:
ornekMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [67]:
ornekMatrixDizim[0]

array([10, 20, 30])

In [68]:
ornekMatrixDizim[1][2]

40

In [69]:
ornekMatrixDizim[1,2]

40

In [70]:
ornekMatrixDizim[1:,2]

array([40, 60])

In [71]:
ornekMatrixDizim[1:,2:]

array([[40],
       [60]])

In [73]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [74]:
yeniMatrix = np.array(yeniListe)

In [75]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [76]:
yeniMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## operasyonlar

In [77]:
yeniBirDizi = np.random.randint(1,100,20)

In [78]:
yeniBirDizi

array([36, 36, 91, 94, 56,  9, 39, 90, 98, 60, 83, 73, 17, 28, 20, 75, 95,
        3, 51, 49])

In [79]:
yeniBirDizi > 24

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True, False,
        True,  True])

In [80]:
yeniBirDizi

array([36, 36, 91, 94, 56,  9, 39, 90, 98, 60, 83, 73, 17, 28, 20, 75, 95,
        3, 51, 49])

In [81]:
sonucDizisi = yeniBirDizi > 24

In [82]:
sonucDizisi

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True, False,
        True,  True])

In [83]:
yeniBirDizi

array([36, 36, 91, 94, 56,  9, 39, 90, 98, 60, 83, 73, 17, 28, 20, 75, 95,
        3, 51, 49])

In [85]:
yeniBirDizi[sonucDizisi]

array([36, 36, 91, 94, 56, 39, 90, 98, 60, 83, 73, 28, 75, 95, 51, 49])

In [86]:
yeniBirDizi

array([36, 36, 91, 94, 56,  9, 39, 90, 98, 60, 83, 73, 17, 28, 20, 75, 95,
        3, 51, 49])

In [87]:
yeniBirDizi[yeniBirDizi>24]

array([36, 36, 91, 94, 56, 39, 90, 98, 60, 83, 73, 28, 75, 95, 51, 49])

In [88]:
sonDizi = np.arange(0,24)

In [89]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [90]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [91]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [92]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [93]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [94]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [95]:
np.max(sonDizi)

23

In [96]:
np.min(sonDizi)

0